[package]
name = "theta-protocole"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
theta-core = { workspace = true }
avian2d = { workspace = true }
bevy = { workspace = true }
lightyear = { workspace = true }
lightyear_avian2d = { workspace = true }
serde = { workspace = true }
