[workspace]
resolver = "3"
members = [
    "crates/theta-core",
    "crates/theta-protocole",
    "crates/theta-client",
    "crates/theta-server",
    "crates/theta-render",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "MIT"

[workspace.dependencies]
# Crates internes
theta-core = { path = "crates/theta-core" }
theta-protocole = { path = "crates/theta-protocole" }
theta-client = { path = "crates/theta-client" }
theta-server = { path = "crates/theta-server" }
theta-render = { path = "crates/theta-render" }

# Dépendances externes
bevy = { version = "0.19", default-features = false, features = [
    "std",
    "multi_threaded",
    "async_executor",
    "bevy_log",
    "bevy_state",
] }
avian2d = { version = "0.7", default-features = false, features = [
    "2d",
    "f32",
    "parry-f32",
    "parallel",
    "serialize",
] }
lightyear = { version = "0.29", default-features = false, features = [
    "std",
    "udp",
    "replication",
    "prediction",
    "interpolation",
    "frame_interpolation",
    "input_native",
    "avian2d",
    "netcode",
] }
lightyear_avian2d = { version = "0.29", features = ["2d"] }
clap = { version = "4.6", features = ["derive"] }
serde = { version = "1", features = ["derive"] }

[profile.dev.package."*"]
opt-level = 3
